DROP DATABASE IF EXISTS bookstore;
CREATE DATABASE bookstore;
USE bookstore;


CREATE TABLE books(
	id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(20) NOT NULL,
    year CHAR(5) NOT NULL,
    pages VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);
INSERT INTO BOOKS VALUES (1,'Title1',1937,146);
INSERT INTO BOOKS VALUES (2,'Title2',1984,42);
INSERT INTO BOOKS VALUES (3,'Title3',2007,228);
INSERT INTO BOOKS VALUES (4,'Title4',2014,220);
INSERT INTO BOOKS VALUES (5,'Title5',2018,1337);

SELECT * FROM BOOKS;
SELECT * FROM BOOKS WHERE ID=1 OR ID=2 OR ID=3;
SELECT * FROM BOOKS WHERE ID=1 OR ID=2 OR ID=3 OR ID=4 OR ID=5;
SELECT * FROM BOOKS WHERE title='TITLE1';
SELECT * FROM BOOKS WHERE TITLE  LIKE 'w%';
SELECT * FROM BOOKS WHERE (year>2011 AND year<2015);

UPDATE BOOKS SET pages=100 WHERE ID=1 OR ID=2;
SELECT * FROM BOOKS;

UPDATE BOOKS SET pages=999 WHERE (pages>220);
SELECT * FROM BOOKS;

DELETE FROM BOOKS WHERE (year<1960);
SELECT * FROM BOOKS;